apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-qos
  namespace: norequests
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx-qos
  template:
    metadata:
      labels:
        app: nginx-qos
    spec:
      containers:
      - image: nginx
        name: nginx-qos
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 32Mi